### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#11]
Ping: https://github.com/openjournals/joss-reviews/issues/6126

The JOSS checklist asks:

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I think it would be good to add an example to the docs, perhaps in the form of a walk-through tutorial. This would make adoption for users much easier.

**Comment by fladd** [comment]
Thanks for the comment. I will think about how to best implement this.

**Comment by fladd** [comment]
We have implemented this now. Thanks again for the suggestion.
