### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#12]
Ping: https://github.com/openjournals/joss-reviews/issues/6126

The checklist asks:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

This is mostly absent from all parts of the project, and I think this should definitely be addressed in order to make the project more contributor-friendly. A common approach is to have a `CONTRIBUTING` file in the repo's root directory that describes everything anyone would need to know in order to contribute, from creating issues to contributing code (and how to test their code contributions). The same content, or a slight variation of it, could be added to the user documentation, e.g. under a "For developers" section.

**Comment by fladd** [comment]
Thanks for the suggestion. Can you maybe point me to an example for this file? We are not doing anything special with respect to contributions (i.e. we do accept pull requests and issues on GitHub), so I am not entirely sure what should go in there exactly. It seems that in our case, such a file could just point to the GitHub documentation on [creating issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) and [creating pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) (they explain this very well I think, and I am not sure what I could do better).

**Comment by jsheunis** [comment]
Sure, here are a few examples, with varying detail/complexity/approaches:

- Numpy: https://github.com/numpy/numpy?tab=readme-ov-file#call-for-contributions
- datalad: https://github.com/datalad/datalad/blob/maint/CONTRIBUTING.md
- nilearn: https://github.com/nilearn/nilearn/blob/main/CONTRIBUTING.rst and https://nilearn.github.io/stable/development.html#contributing
- datalad-catalog: https://github.com/datalad/datalad-catalog#7-contributing
- scikit-image: https://scikit-image.org/docs/stable/development/contribute.html

The github resources are definitely useful, but they don't convey the complete picture of what contributing could mean, and what form it could take.

**Comment by fladd** [comment]
Thanks, we will implement this.
