### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by jsheunis** [fladd/ScanSessionTool#8]
_Ping: https://github.com/openjournals/joss-reviews/issues/6126_

There's a typo in the docs, under `Documentation/Usage`:

> The user interface is organized into three different areas, each hol- ding

**Comment by jsheunis** [comment]
And another one under `Documentation/Usage/The "Documents" area`

> The (f)MRI screening **from** provided by the scanning institution

**Comment by jsheunis** [comment]
And in `Documentation/Usage/The "Measurements" area`

> Click- ing on "Add Measurement" will create

The random word splitting appears elsewhere too, so I guess this text was copied from a place where the word splitting was necessaray. But here it isn't.

**Comment by fladd** [comment]
Thanks, will fix!

**Comment by fladd** [comment]
Fixed in https://github.com/fladd/ScanSessionTool/commit/4c07d8cc9f8e7a358db98ff525f493f120549e92 and https://github.com/fladd/ScanSessionTool/commit/eb270ee63e5a612ac464a3bb2c14a939219b1279
